name: CI/CD Pipeline for My Wedding App

on:
  push:
    branches:
      - main # You can change this to the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main # You can also trigger the workflow on PRs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # You can adjust this to match your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Compile TypeScript to JavaScript
      - name: Compile TypeScript
        run: npx tsc

      # Step 5: Deploy to VPS using SSH
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # The SSH private key from GitHub secrets
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }} # The VPS IP from GitHub secrets
          REMOTE_USER: ${{ secrets.REMOTE_USER }} # The VPS user from GitHub secrets
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r ./dist $REMOTE_USER@$REMOTE_HOST:/path/to/your/app
          ssh -i private_key.pem $REMOTE_USER@$REMOTE_HOST 'pm2 restart my-wedding-app || pm2 start /path/to/your/app/dist/app.js --name my-wedding-app'
          rm private_key.pem
